server.port: 9090

# Security Configuration
spring:
  application.name: auth-needed
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://localhost:18443/realms/jxhui
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
 
# JWT Configuration
jwt:
  auth:
    converter:
      resource-id: root
      principal-attribute: x509-dn-mapper

# Logging Configuration
logging:
  level:
    org:
      springframework:
        security: DEBUG
